// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/jflex/reglas.flex

package org.example;

import java_cup.runtime.*;
import java.util.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\2\2\1\22\0\1\1\1\3\1\4"+
    "\3\0\1\5\1\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\10\20\1\21\1\22"+
    "\1\23\1\24\1\25\2\0\1\26\4\27\1\30\1\31"+
    "\1\27\1\32\2\27\1\33\1\27\1\34\1\35\2\27"+
    "\1\36\1\37\1\40\6\27\1\41\1\0\1\42\1\0"+
    "\1\43\1\0\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\2\27\1\55\1\56\1\57\1\60"+
    "\1\61\1\27\1\62\1\63\1\64\2\27\1\65\3\27"+
    "\1\66\1\67\1\70\7\0\1\2\32\0\1\2\u01df\0"+
    "\1\2\177\0\13\2\35\0\2\2\5\0\1\2\57\0"+
    "\1\2\240\0\1\2\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\2\2\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\2\14\1\2\1\15"+
    "\1\16\1\2\1\17\4\1\1\20\1\21\1\22\6\1"+
    "\1\23\1\2\1\24\1\25\1\0\1\26\1\27\1\30"+
    "\3\0\1\31\1\32\1\33\1\34\7\1\1\35\3\1"+
    "\1\36\1\0\1\37\1\40\1\1\1\41\10\1\2\0"+
    "\3\1\1\42\6\1\2\0\1\43\6\1\1\44\1\45"+
    "\1\3\1\0\1\46\3\1\1\47\1\1\6\0\4\1"+
    "\3\0\1\3\1\0\2\1\2\0\1\3\1\0\2\1"+
    "\4\0\2\1\6\0\1\3\14\0\1\50\2\0\1\51"+
    "\4\0\1\52\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\u0156\0\u018f\0\u01c8\0\u0201"+
    "\0\u023a\0\71\0\u0273\0\u02ac\0\u02e5\0\u031e\0\u0357\0\u0390"+
    "\0\u03c9\0\71\0\71\0\71\0\u0402\0\u043b\0\u0474\0\u04ad"+
    "\0\u04e6\0\u051f\0\71\0\u0558\0\71\0\71\0\344\0\71"+
    "\0\71\0\u0156\0\u0591\0\u05ca\0\u0603\0\71\0\71\0\71"+
    "\0\71\0\u063c\0\u0675\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792"+
    "\0\u031e\0\u07cb\0\u0804\0\u083d\0\71\0\u0876\0\u05ca\0\71"+
    "\0\u08af\0\u031e\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u031e"+
    "\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c"+
    "\0\u031e\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\u031e"+
    "\0\u031e\0\u0eeb\0\u0f24\0\u031e\0\u0f5d\0\u0f96\0\u0fcf\0\u031e"+
    "\0\u1008\0\u1041\0\u107a\0\u0eeb\0\u10b3\0\u10ec\0\u1125\0\u115e"+
    "\0\u1197\0\u11d0\0\u1209\0\u1242\0\u127b\0\u12b4\0\u107a\0\u12ed"+
    "\0\u1326\0\u135f\0\u1398\0\u13d1\0\u140a\0\u1443\0\u147c\0\u14b5"+
    "\0\u14ee\0\u140a\0\u1527\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644"+
    "\0\u167d\0\u16b6\0\u16ef\0\u1728\0\71\0\u1761\0\u179a\0\u17d3"+
    "\0\u180c\0\u1845\0\u187e\0\u18b7\0\u18f0\0\u1929\0\u1962\0\u199b"+
    "\0\u19d4\0\71\0\u1a0d\0\u1a46\0\71\0\u1a7f\0\u1ab8\0\u1af1"+
    "\0\u1b2a\0\71\0\71";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\2\20"+
    "\1\21\1\22\1\23\1\24\1\25\2\26\1\27\1\26"+
    "\1\30\4\26\1\31\1\26\1\32\1\33\1\34\3\26"+
    "\1\35\1\36\1\37\2\26\1\40\4\26\1\41\3\26"+
    "\1\42\1\43\1\44\1\45\72\0\1\3\113\0\1\46"+
    "\45\0\2\47\1\0\1\50\11\0\3\47\5\0\13\47"+
    "\3\0\22\47\10\0\1\51\101\0\3\52\65\0\1\53"+
    "\67\0\1\52\1\0\3\20\24\0\1\54\37\0\1\52"+
    "\1\0\3\20\71\0\1\55\2\0\1\56\70\0\1\57"+
    "\70\0\1\60\70\0\1\61\62\0\3\26\5\0\13\26"+
    "\2\0\23\26\21\0\3\26\5\0\5\26\1\62\5\26"+
    "\2\0\23\26\21\0\3\26\5\0\6\26\1\63\4\26"+
    "\2\0\23\26\21\0\3\26\5\0\12\26\1\64\2\0"+
    "\23\26\21\0\3\26\5\0\13\26\2\0\5\26\1\65"+
    "\15\26\21\0\3\26\5\0\13\26\2\0\12\26\1\66"+
    "\1\26\1\67\6\26\21\0\3\26\5\0\13\26\2\0"+
    "\11\26\1\70\11\26\21\0\3\26\5\0\13\26\2\0"+
    "\6\26\1\71\14\26\21\0\3\26\5\0\13\26\2\0"+
    "\17\26\1\72\3\26\21\0\3\26\5\0\13\26\2\0"+
    "\10\26\1\73\6\26\1\74\3\26\72\0\1\75\11\0"+
    "\1\76\76\0\2\77\75\0\1\100\62\0\3\26\5\0"+
    "\7\26\1\101\3\26\2\0\23\26\21\0\3\26\5\0"+
    "\12\26\1\102\2\0\23\26\21\0\3\26\5\0\10\26"+
    "\1\103\2\26\2\0\23\26\21\0\3\26\5\0\13\26"+
    "\2\0\3\26\1\104\17\26\21\0\3\26\5\0\13\26"+
    "\2\0\20\26\1\105\2\26\21\0\3\26\5\0\13\26"+
    "\2\0\4\26\1\106\16\26\21\0\3\26\5\0\13\26"+
    "\2\0\12\26\1\107\10\26\21\0\3\26\5\0\13\26"+
    "\2\0\15\26\1\110\5\26\21\0\3\26\5\0\13\26"+
    "\2\0\11\26\1\111\11\26\21\0\3\26\5\0\13\26"+
    "\2\0\11\26\1\112\11\26\3\0\10\76\1\113\4\76"+
    "\1\114\53\76\16\0\3\26\5\0\1\115\12\26\2\0"+
    "\23\26\21\0\3\26\5\0\4\26\1\116\6\26\2\0"+
    "\23\26\21\0\3\26\5\0\13\26\2\0\12\26\1\117"+
    "\10\26\21\0\3\26\5\0\13\26\2\0\5\26\1\120"+
    "\15\26\21\0\3\26\5\0\13\26\2\0\4\26\1\121"+
    "\11\26\1\122\4\26\21\0\3\26\5\0\13\26\2\0"+
    "\21\26\1\123\1\26\21\0\3\26\5\0\13\26\2\0"+
    "\7\26\1\124\13\26\21\0\3\26\5\0\13\26\2\0"+
    "\12\26\1\125\10\26\21\0\3\26\5\0\13\26\2\0"+
    "\21\26\1\126\1\26\3\0\10\76\1\113\4\76\1\127"+
    "\63\76\1\113\4\76\1\130\53\76\16\0\3\26\5\0"+
    "\12\26\1\131\2\0\23\26\21\0\3\26\5\0\6\26"+
    "\1\132\4\26\2\0\23\26\21\0\3\26\5\0\13\26"+
    "\2\0\1\26\1\133\21\26\21\0\3\26\5\0\13\26"+
    "\2\0\5\26\1\134\15\26\21\0\3\26\5\0\13\26"+
    "\2\0\17\26\1\135\3\26\21\0\3\26\5\0\13\26"+
    "\2\0\5\26\1\136\15\26\21\0\3\26\5\0\13\26"+
    "\2\0\17\26\1\137\3\26\21\0\3\26\5\0\13\26"+
    "\2\0\5\26\1\140\15\26\21\0\3\26\5\0\13\26"+
    "\2\0\5\26\1\141\15\26\3\0\10\76\1\113\4\76"+
    "\1\142\63\76\1\143\4\76\1\130\53\76\16\0\3\26"+
    "\5\0\3\26\1\144\7\26\2\0\23\26\21\0\3\26"+
    "\5\0\13\26\2\0\17\26\1\145\3\26\21\0\3\26"+
    "\5\0\13\26\2\0\3\26\1\146\17\26\21\0\3\26"+
    "\5\0\13\26\2\0\15\26\1\147\5\26\21\0\3\26"+
    "\5\0\13\26\2\0\17\26\1\150\3\26\21\0\3\26"+
    "\5\0\13\26\2\0\1\26\1\151\21\26\3\0\10\152"+
    "\1\153\4\152\1\154\53\152\10\155\1\156\4\155\1\157"+
    "\53\155\16\0\3\26\5\0\13\26\2\0\5\26\1\160"+
    "\15\26\21\0\3\26\5\0\13\26\2\0\12\26\1\161"+
    "\10\26\21\0\3\26\5\0\13\26\2\0\7\26\1\162"+
    "\13\26\21\0\3\26\5\0\13\26\2\0\13\26\1\163"+
    "\7\26\3\0\15\152\1\164\53\152\10\153\1\165\60\153"+
    "\10\155\1\156\70\155\1\156\4\155\1\166\63\155\1\156"+
    "\4\155\1\167\53\155\14\0\1\170\1\0\3\26\5\0"+
    "\13\26\2\0\23\26\21\0\3\26\5\0\13\26\2\0"+
    "\1\26\1\171\21\26\21\0\3\26\5\0\13\26\2\0"+
    "\17\26\1\172\3\26\17\0\1\173\1\0\3\26\5\0"+
    "\13\26\2\0\23\26\3\0\15\152\1\154\53\152\10\153"+
    "\1\165\4\153\1\174\53\153\10\155\1\156\4\155\1\175"+
    "\53\155\63\0\1\176\23\0\3\26\5\0\13\26\2\0"+
    "\17\26\1\177\3\26\21\0\3\26\5\0\13\26\2\0"+
    "\1\26\1\200\21\26\66\0\1\201\5\0\10\153\1\165"+
    "\4\153\1\202\53\153\10\202\1\203\60\202\50\0\1\204"+
    "\36\0\3\26\5\0\13\26\2\0\5\26\1\205\15\26"+
    "\21\0\3\26\5\0\13\26\2\0\13\26\1\206\7\26"+
    "\53\0\1\207\20\0\10\202\1\203\4\202\1\210\53\202"+
    "\46\0\1\211\36\0\1\212\1\0\3\26\5\0\13\26"+
    "\2\0\23\26\17\0\1\213\1\0\3\26\5\0\13\26"+
    "\2\0\23\26\51\0\1\214\22\0\10\202\1\203\4\202"+
    "\1\215\53\202\64\0\1\216\67\0\1\217\70\0\1\220"+
    "\71\0\1\221\60\0\1\222\64\0\1\223\70\0\1\224"+
    "\74\0\1\225\74\0\1\226\56\0\1\227\70\0\1\230"+
    "\102\0\1\231\67\0\1\232\75\0\1\233\70\0\1\234"+
    "\63\0\1\235\65\0\1\236\70\0\1\237\74\0\1\240"+
    "\70\0\1\241\67\0\1\242\70\0\1\243\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7011];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\4\1\6\11\5\1\1\11\7\1\3\11"+
    "\6\1\1\11\1\1\2\11\1\0\2\11\1\1\3\0"+
    "\4\11\13\1\1\11\1\0\1\1\1\11\12\1\2\0"+
    "\12\1\2\0\12\1\1\0\6\1\6\0\4\1\3\0"+
    "\1\1\1\0\2\1\2\0\1\1\1\0\2\1\4\0"+
    "\2\1\6\0\1\11\14\0\1\11\2\0\1\11\4\0"+
    "\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public List<Symbol> symbolsTable = new ArrayList<>();

    public List<String> errors = new ArrayList<>();

    private Symbol rangoEnteroAceptable(String value){
        Long i = Long.parseLong(value);

        if (i < -32768 || i > 32767){
            errors.add("["+ yyline + ":" + yycolumn + "] - Constante entera fuera de rango [-32768, 32767]: " + value);
        }

        String name = "_"+value;

        return new Symbol(sym.CTE_E, yyline, yycolumn, name);
    }

    private Symbol rangoFloatAceptable(String value){
        double f = Double.parseDouble(value);

        if (f < -2147483648.0D || f > 2147483647.0D){
            errors.add("["+ yyline + ":" + yycolumn + "] - Constante float fuera de rango [-2147483648, 2147483647]: " + value);
        }

        String name = "_"+value;

        return new Symbol(sym.CTE_F, yyline, yycolumn, name);
    }

    private Symbol largoCadenaAceptable(String value){
        if (value.length() > 30){
            errors.add("["+ yyline + ":" + yycolumn + "] - Constante string '" + value + "'" + " muy larga. Max 30 caracteres");
        }

        String name = "_"+value.replace("\"", "");

        return new Symbol(sym.CTE_STR, yyline, yycolumn, name);
    }

    private void addIfNotExists(Symbol symbol){
        if (symbol == null) return;

        boolean already_exists = false;

        for (Symbol s: this.symbolsTable){
            if (s.value.equals(symbol.value)){
                already_exists = true;
                break;
            }
        }

        if (!already_exists) this.symbolsTable.add(symbol);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return new Symbol(sym.EOF, null);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { Symbol symbol = new Symbol(sym.ID, yytext());

                        addIfNotExists(symbol);

                        return symbol;
            }
            // fall through
          case 44: break;
          case 2:
            { errors.add("["+ yyline + ":" + yycolumn + "] - No se encontro un token para el lexema: " + yytext());
            }
            // fall through
          case 45: break;
          case 3:
            { /* Se ignoran */
            }
            // fall through
          case 46: break;
          case 4:
            { return new Symbol(sym.OPL_NOT, yyline, yycolumn, yytext());
            }
            // fall through
          case 47: break;
          case 5:
            { return new Symbol(sym.A_PARENT, yyline, yycolumn, yytext());
            }
            // fall through
          case 48: break;
          case 6:
            { return new Symbol(sym.C_PARENT, yyline, yycolumn, yytext());
            }
            // fall through
          case 49: break;
          case 7:
            { return new Symbol(sym.OP_MULTIPLICACION, yyline, yycolumn, yytext());
            }
            // fall through
          case 50: break;
          case 8:
            { return new Symbol(sym.OP_SUMA, yyline, yycolumn, yytext());
            }
            // fall through
          case 51: break;
          case 9:
            { return new Symbol(sym.COMA, yyline, yycolumn, yytext());
            }
            // fall through
          case 52: break;
          case 10:
            { return new Symbol(sym.OP_RESTA, yyline, yycolumn, yytext());
            }
            // fall through
          case 53: break;
          case 11:
            { return new Symbol(sym.OP_DIVISION, yyline, yycolumn, yytext());
            }
            // fall through
          case 54: break;
          case 12:
            { Symbol symbol = rangoEnteroAceptable(yytext());

                        addIfNotExists(symbol);

                        return symbol;
            }
            // fall through
          case 55: break;
          case 13:
            { return new Symbol(sym.PYC, yyline, yycolumn, yytext());
            }
            // fall through
          case 56: break;
          case 14:
            { return new Symbol(sym.OP_MENOR, yyline, yycolumn, yytext());
            }
            // fall through
          case 57: break;
          case 15:
            { return new Symbol(sym.OP_MAYOR, yyline, yycolumn, yytext());
            }
            // fall through
          case 58: break;
          case 16:
            { return new Symbol(sym.A_CORCHETE, yyline, yycolumn, yytext());
            }
            // fall through
          case 59: break;
          case 17:
            { return new Symbol(sym.C_CORCHETE, yyline, yycolumn, yytext());
            }
            // fall through
          case 60: break;
          case 18:
            { return new Symbol(sym.GUION_BAJO, yyline, yycolumn, yytext());
            }
            // fall through
          case 61: break;
          case 19:
            { return new Symbol(sym.A_LLAVE, yyline, yycolumn, yytext());
            }
            // fall through
          case 62: break;
          case 20:
            { return new Symbol(sym.C_LLAVE, yyline, yycolumn, yytext());
            }
            // fall through
          case 63: break;
          case 21:
            { return new Symbol(sym.OP_DIST, yyline, yycolumn, yytext());
            }
            // fall through
          case 64: break;
          case 22:
            { Symbol symbol = largoCadenaAceptable(yytext());

                        addIfNotExists(symbol);

                        return symbol;
            }
            // fall through
          case 65: break;
          case 23:
            { return new Symbol(sym.OPL_AND, yyline, yycolumn, yytext());
            }
            // fall through
          case 66: break;
          case 24:
            { Symbol symbol = rangoFloatAceptable(yytext());

                        addIfNotExists(symbol);

                        return symbol;
            }
            // fall through
          case 67: break;
          case 25:
            { return new Symbol(sym.OP_DECLARACION, yyline, yycolumn, yytext());
            }
            // fall through
          case 68: break;
          case 26:
            { return new Symbol(sym.OP_MENOR_IG, yyline, yycolumn, yytext());
            }
            // fall through
          case 69: break;
          case 27:
            { return new Symbol(sym.OP_IGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 70: break;
          case 28:
            { return new Symbol(sym.OP_MAYOR_IG, yyline, yycolumn, yytext());
            }
            // fall through
          case 71: break;
          case 29:
            { return new Symbol(sym.IF, yyline, yycolumn, yytext());
            }
            // fall through
          case 72: break;
          case 30:
            { return new Symbol(sym.OPL_OR, yyline, yycolumn, yytext());
            }
            // fall through
          case 73: break;
          case 31:
            { String binValue = String.valueOf(yytext()).substring(2);
                        Integer decValue = Integer.parseInt(binValue, 2);
                        String decValueStr = String.valueOf(decValue);

                        Symbol symbol = new Symbol(sym.CTE_B, yytext());

                        addIfNotExists(symbol);

                        return symbol;
            }
            // fall through
          case 74: break;
          case 32:
            { return new Symbol(sym.OP_ASIGNACION, yyline, yycolumn, yytext());
            }
            // fall through
          case 75: break;
          case 33:
            { return new Symbol(sym.TYPE_INT, yyline, yycolumn, yytext());
            }
            // fall through
          case 76: break;
          case 34:
            { return new Symbol(sym.ELSE, yyline, yycolumn, yytext());
            }
            // fall through
          case 77: break;
          case 35:
            { return new Symbol(sym.TYPE_FLOAT, yyline, yycolumn, yytext());
            }
            // fall through
          case 78: break;
          case 36:
            { return new Symbol(sym.WHILE, yyline, yycolumn, yytext());
            }
            // fall through
          case 79: break;
          case 37:
            { return new Symbol(sym.WRITE, yyline, yycolumn, yytext());
            }
            // fall through
          case 80: break;
          case 38:
            { return new Symbol(sym.TYPE_STRING, yyline, yycolumn, yytext());
            }
            // fall through
          case 81: break;
          case 39:
            { return new Symbol(sym.FILTER, yyline, yycolumn, yytext());
            }
            // fall through
          case 82: break;
          case 40:
            { return new Symbol(sym.INI_DECLARE, yyline, yycolumn, yytext());
            }
            // fall through
          case 83: break;
          case 41:
            { return new Symbol(sym.INI_PROGRAM, yyline, yycolumn, yytext());
            }
            // fall through
          case 84: break;
          case 42:
            { return new Symbol(sym.END_DECLARE, yyline, yycolumn, yytext());
            }
            // fall through
          case 85: break;
          case 43:
            { return new Symbol(sym.END_PROGRAM, yyline, yycolumn, yytext());
            }
            // fall through
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
