
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_MAYOR = 17;
  public static final int INI_PROGRAM = 28;
  public static final int A_PARENT = 39;
  public static final int OP_MAYOR_IG = 19;
  public static final int FILTER = 38;
  public static final int OP_MULTIPLICACION = 10;
  public static final int INI_DECLARE = 26;
  public static final int C_CORCHETE = 31;
  public static final int WRITE = 37;
  public static final int C_LLAVE = 25;
  public static final int END_PROGRAM = 29;
  public static final int A_LLAVE = 24;
  public static final int C_PARENT = 40;
  public static final int END_DECLARE = 27;
  public static final int TYPE_INT = 35;
  public static final int CTE_F = 6;
  public static final int CTE_E = 4;
  public static final int OPL_OR = 14;
  public static final int IF = 22;
  public static final int CTE_B = 5;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int OP_MENOR_IG = 18;
  public static final int OP_DIVISION = 11;
  public static final int error = 1;
  public static final int OP_DECLARACION = 32;
  public static final int COMA = 33;
  public static final int OP_RESTA = 9;
  public static final int TYPE_FLOAT = 34;
  public static final int OP_ASIGNACION = 3;
  public static final int GUION_BAJO = 41;
  public static final int ELSE = 23;
  public static final int OP_IGUAL = 20;
  public static final int TYPE_STRING = 36;
  public static final int CTE_STR = 7;
  public static final int WHILE = 12;
  public static final int A_CORCHETE = 30;
  public static final int OP_SUMA = 8;
  public static final int OP_DIST = 21;
  public static final int OPL_NOT = 15;
  public static final int OPL_AND = 13;
  public static final int PYC = 42;
  public static final int OP_MENOR = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "OP_ASIGNACION",
  "CTE_E",
  "CTE_B",
  "CTE_F",
  "CTE_STR",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULTIPLICACION",
  "OP_DIVISION",
  "WHILE",
  "OPL_AND",
  "OPL_OR",
  "OPL_NOT",
  "OP_MENOR",
  "OP_MAYOR",
  "OP_MENOR_IG",
  "OP_MAYOR_IG",
  "OP_IGUAL",
  "OP_DIST",
  "IF",
  "ELSE",
  "A_LLAVE",
  "C_LLAVE",
  "INI_DECLARE",
  "END_DECLARE",
  "INI_PROGRAM",
  "END_PROGRAM",
  "A_CORCHETE",
  "C_CORCHETE",
  "OP_DECLARACION",
  "COMA",
  "TYPE_FLOAT",
  "TYPE_INT",
  "TYPE_STRING",
  "WRITE",
  "FILTER",
  "A_PARENT",
  "C_PARENT",
  "GUION_BAJO",
  "PYC"
  };
}

